# -*- coding: utf-8 -*-

# Define here the models for your scraped items
#
# See documentation in:
# http://doc.org/en/latest/topics/items.html

from scrapy import Item, Field

class SalaryItem(Item):
    scrape_date = Field()
    scrape_time = Field()
    company_name = Field()
    salaries_cnt = Field()
    jobs_count = Field()
    position = Field()
    position_url = Field()
    pos_cnt = Field()
    avg_sal = Field()
    low_sal = Field()
    high_sal = Field()
    company_name = Field()
    updated = Field()
    salaries_page_url = Field()
    total_compensation = Field()
    base_pay = Field()
    total_pay_low = Field()
    total_pay_high = Field()
    cash_bonuses_cnt = Field()
    cash_bonuses_avg = Field()
    cash_bonuses_low = Field()
    cash_bonuses_high = Field()
    stock_cnt = Field()
    stock_avg = Field()
    stock_low = Field()
    stock_high = Field()

class ReviewItem(Item):
    scrape_date = Field()
    scrape_time = Field()
    company_name = Field()
    reviewUrl = Field()
    reviewDate = Field()
    title = Field()
    rating = Field()
    currentFormer = Field()
    position = Field()
    location = Field()
    fullPartTime = Field()
    tenure = Field()
    pros = Field()
    cons = Field()
    advice = Field()
    sq1Color = Field()
    sq1Txt = Field()
    sq2Color = Field()
    sq2Txt = Field()
    sq3Color = Field()
    sq3Txt = Field()

class InterviewItem(Item):
    scrape_date = Field()
    scrape_time = Field()
    interviewUrl = Field()
    interviewsCnt = Field()
    company = Field()
    updated = Field()
    interDif = Field()
    posInter = Field()
    neutInter = Field()
    negInter = Field()
    getAnInt1Desc = Field()
    getAnInt1Perc = Field()
    getAnInt2Desc = Field()
    getAnInt2Perc = Field()
    getAnInt3Desc = Field()
    getAnInt3Perc = Field()
    getAnInt4Desc = Field()
    getAnInt4Perc = Field()
    getAnInt5Desc = Field()
    getAnInt5Perc = Field()
    getAnInt6Desc = Field()
    getAnInt6Perc = Field()
    getAnInt7Desc = Field()
    getAnInt7Perc = Field()
    reviewDate = Field()
    position = Field()
    location = Field()
    dateInterview = Field()
    appDetails = Field()
    interDetails = Field()
    interQuestions = Field()
    negotDetails = Field()
    sq1Color = Field()
    sq1Txt = Field()
    sq2Color = Field()
    sq2Txt = Field()
    sq3Color = Field()
    sq3Txt = Field()
    numberHelpful = Field()

class CompanyInfoItem(Item):
    company_name = Field()
    scrape_date = Field()
    scrape_time = Field()
    AverageRating = Field()
    ReviewsCNT = Field()
    RecToFriend = Field()
    ApprCEO = Field()
    CEOName = Field()
    CEORateCNT = Field()
    CompanyWebsite = Field()
    Size = Field()
    Type = Field()
    Ticker = Field()
    Revenue = Field()
    HQ = Field()
    Founded = Field()
    Industry = Field()
    Competitors = Field()
    Text = Field()
    Mission = Field()

class CompanyUrlsItem(Item):
    scrape_date = Field()
    scrape_time = Field()
    company_name = Field()
    salaries_url = Field()
    overview_url = Field()
    reviews_url = Field()
    interviews_url = Field()

